version: '2.4'

services:
  
  server1:
    build: .
    ports:
      - "8081:8080"
    mem_limit: 500m
    #cpus: 1
    networks:
      - main-net
  
  server2:
    build: .
    ports:
      - "8082:8080"
    mem_limit: 500m
    #cpus: 0.7
    networks:
      - main-net
  
  server3:
    build: .
    ports:
      - "8083:8080"
    mem_limit: 500m
    #cpus: 0.3
    networks:
      - main-net

  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy_lb
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - main-net

networks:
  main-net:
    driver: bridge